%% Script to check the keypoints generated by the RenderForCNN Pipeline. You need to specofy the image name and the 
%% annotations file name for which you want to check.
clc;close all;clear all;
%% Specify the image name : 
imname ='167df2c10c116eb5d61b6a34f3fd808c_a344_e002_t008_d010';
%% To display the annotations without any cropping or background overlaying.
img = imread(['/tmp/sarthaksharma/syn_images_keypoints/' ,imname,'.png']);
annotations =  importdata(['../data/syn_keypoint_annotations/',imname,'.txt']);
f1=figure,imshow(img);hold on;scatter(annotations(:,1),annotations(:,2),'r','Filled');

disp('==> Done for normal')
%% Display annotations with cropping
img = imread(['/tmp/sarthaksharma/syn_images_keypoints_cropped/' ,imname,'.png']);
annotationsCropped =  importdata(['../data/syn_keypoint_annotations_cropped/',imname,'.txt']);
f2=figure,imshow(img);hold on;
scatter(annotationsCropped(find(annotationsCropped(:,1)~=-1),1),annotationsCropped(find(annotationsCropped(:,2)~=-1),2),'r','Filled');
disp('==> Done for cropped')
%% Display annotations with cropping and background overlaying.
% NOTE that the extesion of image here changes to jpg coz of
% blender.Ideally the annotations should remain same, but as we made change
% to the 'overlay_background_batcj_keypoints.m' to suit the needs of
% hourglass,annotations change.
img = imread(['/tmp/sarthaksharma/syn_images_keypoints_cropped_bkg_overlaid/' ,imname,'.jpg']);
annotationsBackgroundCropped =  importdata(['../data/syn_keypoint_annotations_cropped_bkg_overlaid/',imname,'.txt']);
f3=figure,imshow(img);hold on;scatter(annotationsBackgroundCropped(find(annotationsBackgroundCropped(:,1)~=-1),1),annotationsBackgroundCropped(find(annotationsBackgroundCropped(:,2)~=-1),2),'r','Filled');
disp('==> Done for background overlay')






